services:
  - type: web
    name: creatio-telegram-bridge
    env: python
    plan: free
    branch: main
    buildCommand: |
      pip install --only-binary=:all: -r requirements.txt
    startCommand: |
      uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: YOUR_TELEGRAM_BOT_TOKEN
      - key: CREATIO_BASE_URL
        value: https://your_creatio_site/0/rest
      - key: CREATIO_USERNAME
        value: Supervisor
      - key: CREATIO_PASSWORD
        value: MyPassword123
